// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSFS1FoYc76keZTB3IvJoLP4em4taZFOc',
    appId: '1:820178092971:web:2f83975032b5cd846dc8ee',
    messagingSenderId: '820178092971',
    projectId: 'spajam-2024-hiyokogumi',
    authDomain: 'spajam-2024-hiyokogumi.firebaseapp.com',
    storageBucket: 'spajam-2024-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKmp2ZKoWU183BW1ab1siEYE36jyZCVUI',
    appId: '1:820178092971:android:119a5bec8ef4ccc76dc8ee',
    messagingSenderId: '820178092971',
    projectId: 'spajam-2024-hiyokogumi',
    storageBucket: 'spajam-2024-hiyokogumi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOk2jxb-xD2z393Gkjp3Jdav4_2Gj-JEY',
    appId: '1:820178092971:ios:38087fec7b921f526dc8ee',
    messagingSenderId: '820178092971',
    projectId: 'spajam-2024-hiyokogumi',
    storageBucket: 'spajam-2024-hiyokogumi.appspot.com',
    iosBundleId: 'com.example.spajam2024Hiyokogumi',
  );

}